CREATE TABLE IF NOT EXISTS public.city
(
    id              BIGINT                                                     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            TEXT                                                       NOT NULL CHECK (name <> '')
        CONSTRAINT max_len_name CHECK (LENGTH(name) <= 256),
    translation   TEXT UNIQUE                                     NOT NULL CHECK (translation <> '')
        CONSTRAINT max_len_translation CHECK (LENGTH(translation) <= 256)    
);