CREATE TABLE IF NOT EXISTS public."complain"
(
    id                         BIGINT                                               GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id_complainer         BIGINT                                               NOT NULL REFERENCES public."user" (id),
    user_id_being_complaind    BIGINT                                               NOT NULL REFERENCES public."user" (id),
    complain_type               complain_type                                       NOT NULL ,
    complain_text           TEXT                                                 NOT NULL
        CONSTRAINT max_len_name CHECK (LENGTH(complain_text) <= 2000)  
);