CREATE TABLE IF NOT EXISTS public.complaint
(
    id                         BIGINT                                               GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id_complainer         BIGINT                                               NOT NULL REFERENCES public."user" (id),
    user_id_being_complaind    BIGINT                                               NOT NULL REFERENCES public."user" (id),
    complaint_type               complaint_type                                     NOT NULL ,
    complaint_text           TEXT                                                   NOT NULL
        CONSTRAINT max_len_name CHECK (LENGTH(complaint_text) <= 2000)  
);