CREATE TABLE IF NOT EXISTS public.advert_image
(
    id         BIGINT                                           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url        TEXT                                             NOT NULL CHECK (url <> '')
        CONSTRAINT max_len_url CHECK (LENGTH(url) <= 256),
    advert_id  BIGINT                                           NOT NULL REFERENCES public.advert (id) ON DELETE CASCADE
);