CREATE TABLE IF NOT EXISTS public.order
(
    id         BIGINT                                                             GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT                                                             NOT NULL REFERENCES public."user" (id),
    advert_id  BIGINT                                                             NOT NULL REFERENCES public.advert (id),
    order_status  order_status            DEFAULT 'В корзине'                     NOT NULL,
    created_time TIMESTAMP WITH TIME ZONE DEFAULT NOW()                           NOT NULL,
    updated_time TIMESTAMP WITH TIME ZONE DEFAULT NOW()                           NOT NULL
        CONSTRAINT updated_time_is_after_created_time CHECK (updated_time >= created_time),
    closed_time  TIMESTAMP WITH TIME ZONE DEFAULT NOW()                           NOT NULL
        CONSTRAINT closed_time_is_after_created_time CHECK (closed_time >= created_time),
    phone          TEXT                                                           NOT NULL
        CONSTRAINT max_len_phone CHECK (LENGTH(phone) <= 18),  
    name           TEXT                                                           NOT NULL
        CONSTRAINT max_len_name CHECK (LENGTH(name) <= 256),
    surname       TEXT                                                            NOT NULL
        CONSTRAINT max_len_surname CHECK (LENGTH(surname) <= 256), 
    patronymic    TEXT                                                            NOT NULL
        CONSTRAINT max_len_patronymic CHECK (LENGTH(patronymic) <= 256),  
    email         TEXT                                                            NOT NULL
        CONSTRAINT max_len_email CHECK (LENGTH(email) <= 256)             
    
);