CREATE TABLE IF NOT EXISTS public."profile"
(
    id              BIGINT                                                       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT                                                            NOT NULL REFERENCES public."user" (id),
    city_id    BIGINT                                                                     REFERENCES public."city" (id),
    phone      TEXT UNIQUE DEFAULT NULL
        CONSTRAINT max_len_phone CHECK (LENGTH(phone) <= 18),
    name       TEXT DEFAULT NULL
        CONSTRAINT max_len_name CHECK (LENGTH(name) <= 256),
    surname       TEXT DEFAULT NULL
        CONSTRAINT max_len_surname CHECK (LENGTH(surname) <= 256),    
    regtime TIMESTAMP WITH TIME ZONE DEFAULT NOW()                               NOT NULL,
    verified        BOOLEAN                  DEFAULT FALSE                       NOT NULL,
    avatar_url     TEXT UNIQUE
        CONSTRAINT max_len_avatar_url CHECK (LENGTH(avatar_url) <= 256)
);