CREATE TABLE IF NOT EXISTS public."review"
(
    id        BIGINT                                               GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id   BIGINT                                               NOT NULL REFERENCES public."user" (id),
    advert_id BIGINT                                               NOT NULL REFERENCES public."advert" (id) ON DELETE CASCADE,
    review    TEXT DEFAULT NULL
        CONSTRAINT max_len_review CHECK (LENGTH(review) <= 256),
    created_time    TIMESTAMP WITH TIME ZONE DEFAULT NOW()         NOT NULL, 
    rating    SMALLINT DEFAULT 1
        CONSTRAINT rating_interval CHECK (rating >= 1 and rating <= 5),   
    CONSTRAINT review_uniq_together_advert_id_user_id unique (user_id, advert_id)
);