version: "3.8"

services:
  postgres:
    image: postgres:16.0-alpine3.18
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - ${BACKEND_PORT_POSTGRES}:${BACKEND_PORT_POSTGRES} # [порт компьютера]:[порт контейнера] 5432:5432
    command:
      - "postgres"
      - "-c"
      - "port=${BACKEND_PORT_POSTGRES}"
    volumes:
      - postgres:/var/lib/postgresql/data


  pgadmin:
    image: dpage/pgadmin4:7.8
    environment:
      - PGADMIN_DEFAULT_EMAIL=imao@pgadmin.com
      - PGADMIN_DEFAULT_PASSWORD=password_imao_1337
      - PGADMIN_LISTEN_PORT=${PGADMIN_LISTEN_PORT_ENV}
    ports:
      - ${PG_ADMIN_PORT}:${PGADMIN_LISTEN_PORT_ENV} # [порт компьютера]:[порт контейнера]
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  postgres:
  pgadmin:
 