global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'golang'
    static_configs:
      - targets: ['main:8080']

  - job_name: 'auth'
    static_configs:
      - targets: [ 'auth:7071' ]

  - job_name: 'profile'
    static_configs:
      - targets: [ 'profile:7072' ]

  - job_name: 'cart'
    static_configs:
      - targets: [ 'cart:7073' ]