global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: /prometheus/metrics
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'golang'
    static_configs:
      - targets: ['host.docker.internal:8080']

  - job_name: 'auth'
    static_configs:
      - targets: [ 'host.docker.internal:7071' ]

  - job_name: 'profile'
    static_configs:
      - targets: [ 'host.docker.internal:7072' ]

  - job_name: 'cart'
    static_configs:
      - targets: [ 'host.docker.internal:7073' ]