// Code generated by MockGen. DO NOT EDIT.
// Source: user.go

// Package mock_usecases is a generated GoMock package.
package mock_usecases

import (
	context "context"
	reflect "reflect"

	models "github.com/go-park-mail-ru/2024_1_IMAO/internal/models"
	gomock "github.com/golang/mock/gomock"
)

// MockUsersInfo is a mock of UsersInfo interface.
type MockUsersInfo struct {
	ctrl     *gomock.Controller
	recorder *MockUsersInfoMockRecorder
}

// MockUsersInfoMockRecorder is the mock recorder for MockUsersInfo.
type MockUsersInfoMockRecorder struct {
	mock *MockUsersInfo
}

// NewMockUsersInfo creates a new mock instance.
func NewMockUsersInfo(ctrl *gomock.Controller) *MockUsersInfo {
	mock := &MockUsersInfo{ctrl: ctrl}
	mock.recorder = &MockUsersInfoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsersInfo) EXPECT() *MockUsersInfoMockRecorder {
	return m.recorder
}

// AddSession mocks base method.
func (m *MockUsersInfo) AddSession(email uint) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddSession", email)
	ret0, _ := ret[0].(string)
	return ret0
}

// AddSession indicates an expected call of AddSession.
func (mr *MockUsersInfoMockRecorder) AddSession(email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSession", reflect.TypeOf((*MockUsersInfo)(nil).AddSession), email)
}

// CreateUser mocks base method.
func (m *MockUsersInfo) CreateUser(ctx context.Context, email, passwordHash string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, email, passwordHash)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUsersInfoMockRecorder) CreateUser(ctx, email, passwordHash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUsersInfo)(nil).CreateUser), ctx, email, passwordHash)
}

// EditUser mocks base method.
func (m *MockUsersInfo) EditUser(id uint, email, passwordHash string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditUser", id, email, passwordHash)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EditUser indicates an expected call of EditUser.
func (mr *MockUsersInfoMockRecorder) EditUser(id, email, passwordHash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditUser", reflect.TypeOf((*MockUsersInfo)(nil).EditUser), id, email, passwordHash)
}

// GetLastID mocks base method.
func (m *MockUsersInfo) GetLastID(ctx context.Context) uint {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastID", ctx)
	ret0, _ := ret[0].(uint)
	return ret0
}

// GetLastID indicates an expected call of GetLastID.
func (mr *MockUsersInfoMockRecorder) GetLastID(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastID", reflect.TypeOf((*MockUsersInfo)(nil).GetLastID), ctx)
}

// GetUserByEmail mocks base method.
func (m *MockUsersInfo) GetUserByEmail(ctx context.Context, email string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, email)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockUsersInfoMockRecorder) GetUserByEmail(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockUsersInfo)(nil).GetUserByEmail), ctx, email)
}

// GetUserBySession mocks base method.
func (m *MockUsersInfo) GetUserBySession(ctx context.Context, sessionID string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserBySession", ctx, sessionID)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserBySession indicates an expected call of GetUserBySession.
func (mr *MockUsersInfoMockRecorder) GetUserBySession(ctx, sessionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserBySession", reflect.TypeOf((*MockUsersInfo)(nil).GetUserBySession), ctx, sessionID)
}

// RemoveSession mocks base method.
func (m *MockUsersInfo) RemoveSession(ctx context.Context, sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveSession", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveSession indicates an expected call of RemoveSession.
func (mr *MockUsersInfoMockRecorder) RemoveSession(ctx, sessionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveSession", reflect.TypeOf((*MockUsersInfo)(nil).RemoveSession), ctx, sessionID)
}

// SessionExists mocks base method.
func (m *MockUsersInfo) SessionExists(sessionID string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SessionExists", sessionID)
	ret0, _ := ret[0].(bool)
	return ret0
}

// SessionExists indicates an expected call of SessionExists.
func (mr *MockUsersInfoMockRecorder) SessionExists(sessionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SessionExists", reflect.TypeOf((*MockUsersInfo)(nil).SessionExists), sessionID)
}

// UserExists mocks base method.
func (m *MockUsersInfo) UserExists(ctx context.Context, email string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserExists", ctx, email)
	ret0, _ := ret[0].(bool)
	return ret0
}

// UserExists indicates an expected call of UserExists.
func (mr *MockUsersInfoMockRecorder) UserExists(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserExists", reflect.TypeOf((*MockUsersInfo)(nil).UserExists), ctx, email)
}
