DROP TABLE IF EXISTS public.payments CASCADE;
CREATE TABLE IF NOT EXISTS public.payments
(
    id        BIGINT                                               GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    advert_id BIGINT                                               NOT NULL REFERENCES public.advert (id) ON DELETE CASCADE,
    payment_uuid UUID                                              NOT NULL,
    payment_value INTEGER                                          NOT NULL,
    payment_description   TEXT                                     NOT NULL CHECK (payment_description <> '')
        CONSTRAINT max_len_description CHECK (LENGTH(payment_description) <= 256),
    payment_status   TEXT                                          NOT NULL CHECK (payment_status <> '')
        CONSTRAINT max_len_status CHECK (LENGTH(payment_status) <= 50),
    payment_form_url   TEXT                                        NOT NULL CHECK (payment_form_url <> '')
        CONSTRAINT max_len_form_url CHECK (LENGTH(payment_form_url) <= 512),
    created_time    TIMESTAMP WITH TIME ZONE DEFAULT NOW()         NOT NULL            
);