// Code generated by MockGen. DO NOT EDIT.
// Source: adverts.go

// Package mock_usecases is a generated GoMock package.
package mock_usecases

import (
	context "context"
	multipart "mime/multipart"
	reflect "reflect"

	models "github.com/go-park-mail-ru/2024_1_IMAO/internal/models"
	gomock "github.com/golang/mock/gomock"
)

// MockAdvertsStorageInterface is a mock of AdvertsStorageInterface interface.
type MockAdvertsStorageInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAdvertsStorageInterfaceMockRecorder
}

// MockAdvertsStorageInterfaceMockRecorder is the mock recorder for MockAdvertsStorageInterface.
type MockAdvertsStorageInterfaceMockRecorder struct {
	mock *MockAdvertsStorageInterface
}

// NewMockAdvertsStorageInterface creates a new mock instance.
func NewMockAdvertsStorageInterface(ctrl *gomock.Controller) *MockAdvertsStorageInterface {
	mock := &MockAdvertsStorageInterface{ctrl: ctrl}
	mock.recorder = &MockAdvertsStorageInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdvertsStorageInterface) EXPECT() *MockAdvertsStorageInterfaceMockRecorder {
	return m.recorder
}

// CheckAdvertOwnership mocks base method.
func (m *MockAdvertsStorageInterface) CheckAdvertOwnership(ctx context.Context, advertID, userID uint) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckAdvertOwnership", ctx, advertID, userID)
	ret0, _ := ret[0].(bool)
	return ret0
}

// CheckAdvertOwnership indicates an expected call of CheckAdvertOwnership.
func (mr *MockAdvertsStorageInterfaceMockRecorder) CheckAdvertOwnership(ctx, advertID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAdvertOwnership", reflect.TypeOf((*MockAdvertsStorageInterface)(nil).CheckAdvertOwnership), ctx, advertID, userID)
}

// CloseAdvert mocks base method.
func (m *MockAdvertsStorageInterface) CloseAdvert(ctx context.Context, advertID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseAdvert", ctx, advertID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseAdvert indicates an expected call of CloseAdvert.
func (mr *MockAdvertsStorageInterfaceMockRecorder) CloseAdvert(ctx, advertID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseAdvert", reflect.TypeOf((*MockAdvertsStorageInterface)(nil).CloseAdvert), ctx, advertID)
}

// CreateAdvert mocks base method.
func (m *MockAdvertsStorageInterface) CreateAdvert(ctx context.Context, files []*multipart.FileHeader, data models.ReceivedAdData) (*models.ReturningAdvert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAdvert", ctx, files, data)
	ret0, _ := ret[0].(*models.ReturningAdvert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAdvert indicates an expected call of CreateAdvert.
func (mr *MockAdvertsStorageInterfaceMockRecorder) CreateAdvert(ctx, files, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAdvert", reflect.TypeOf((*MockAdvertsStorageInterface)(nil).CreateAdvert), ctx, files, data)
}

// EditAdvert mocks base method.
func (m *MockAdvertsStorageInterface) EditAdvert(ctx context.Context, files []*multipart.FileHeader, data models.ReceivedAdData) (*models.ReturningAdvert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditAdvert", ctx, files, data)
	ret0, _ := ret[0].(*models.ReturningAdvert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EditAdvert indicates an expected call of EditAdvert.
func (mr *MockAdvertsStorageInterfaceMockRecorder) EditAdvert(ctx, files, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditAdvert", reflect.TypeOf((*MockAdvertsStorageInterface)(nil).EditAdvert), ctx, files, data)
}

// GetAdvert mocks base method.
func (m *MockAdvertsStorageInterface) GetAdvert(ctx context.Context, userID, advertID uint) (*models.ReturningAdvert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdvert", ctx, userID, advertID)
	ret0, _ := ret[0].(*models.ReturningAdvert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAdvert indicates an expected call of GetAdvert.
func (mr *MockAdvertsStorageInterfaceMockRecorder) GetAdvert(ctx, userID, advertID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdvert", reflect.TypeOf((*MockAdvertsStorageInterface)(nil).GetAdvert), ctx, userID, advertID)
}

// GetAdvertOnlyByID mocks base method.
func (m *MockAdvertsStorageInterface) GetAdvertOnlyByID(ctx context.Context, advertID uint) (*models.ReturningAdvert, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdvertOnlyByID", ctx, advertID)
	ret0, _ := ret[0].(*models.ReturningAdvert)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAdvertOnlyByID indicates an expected call of GetAdvertOnlyByID.
func (mr *MockAdvertsStorageInterfaceMockRecorder) GetAdvertOnlyByID(ctx, advertID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdvertOnlyByID", reflect.TypeOf((*MockAdvertsStorageInterface)(nil).GetAdvertOnlyByID), ctx, advertID)
}

// GetAdvertsByCategory mocks base method.
func (m *MockAdvertsStorageInterface) GetAdvertsByCategory(ctx context.Context, category, city string, userID, startID, num uint) ([]*models.ReturningAdInList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdvertsByCategory", ctx, category, city, userID, startID, num)
	ret0, _ := ret[0].([]*models.ReturningAdInList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAdvertsByCategory indicates an expected call of GetAdvertsByCategory.
func (mr *MockAdvertsStorageInterfaceMockRecorder) GetAdvertsByCategory(ctx, category, city, userID, startID, num interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdvertsByCategory", reflect.TypeOf((*MockAdvertsStorageInterface)(nil).GetAdvertsByCategory), ctx, category, city, userID, startID, num)
}

// GetAdvertsByCity mocks base method.
func (m *MockAdvertsStorageInterface) GetAdvertsByCity(ctx context.Context, city string, userID, startID, num uint) ([]*models.ReturningAdInList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdvertsByCity", ctx, city, userID, startID, num)
	ret0, _ := ret[0].([]*models.ReturningAdInList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAdvertsByCity indicates an expected call of GetAdvertsByCity.
func (mr *MockAdvertsStorageInterfaceMockRecorder) GetAdvertsByCity(ctx, city, userID, startID, num interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdvertsByCity", reflect.TypeOf((*MockAdvertsStorageInterface)(nil).GetAdvertsByCity), ctx, city, userID, startID, num)
}

// GetAdvertsForUserWhereStatusIs mocks base method.
func (m *MockAdvertsStorageInterface) GetAdvertsForUserWhereStatusIs(ctx context.Context, userID, authorID, deleted, advertNum uint) ([]*models.ReturningAdInList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdvertsForUserWhereStatusIs", ctx, userID, authorID, deleted, advertNum)
	ret0, _ := ret[0].([]*models.ReturningAdInList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAdvertsForUserWhereStatusIs indicates an expected call of GetAdvertsForUserWhereStatusIs.
func (mr *MockAdvertsStorageInterfaceMockRecorder) GetAdvertsForUserWhereStatusIs(ctx, userID, authorID, deleted, advertNum interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdvertsForUserWhereStatusIs", reflect.TypeOf((*MockAdvertsStorageInterface)(nil).GetAdvertsForUserWhereStatusIs), ctx, userID, authorID, deleted, advertNum)
}

// GetPaymnetUUIDList mocks base method.
func (m *MockAdvertsStorageInterface) GetPaymnetUUIDList(ctx context.Context, advertID uint) (*models.PaymnetUUIDList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPaymnetUUIDList", ctx, advertID)
	ret0, _ := ret[0].(*models.PaymnetUUIDList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPaymnetUUIDList indicates an expected call of GetPaymnetUUIDList.
func (mr *MockAdvertsStorageInterfaceMockRecorder) GetPaymnetUUIDList(ctx, advertID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaymnetUUIDList", reflect.TypeOf((*MockAdvertsStorageInterface)(nil).GetPaymnetUUIDList), ctx, advertID)
}

// GetPriceHistory mocks base method.
func (m *MockAdvertsStorageInterface) GetPriceHistory(ctx context.Context, userID uint) ([]*models.PriceHistoryItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPriceHistory", ctx, userID)
	ret0, _ := ret[0].([]*models.PriceHistoryItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPriceHistory indicates an expected call of GetPriceHistory.
func (mr *MockAdvertsStorageInterfaceMockRecorder) GetPriceHistory(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPriceHistory", reflect.TypeOf((*MockAdvertsStorageInterface)(nil).GetPriceHistory), ctx, userID)
}

// GetPromotionData mocks base method.
func (m *MockAdvertsStorageInterface) GetPromotionData(ctx context.Context, advertID uint) (*models.Promotion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPromotionData", ctx, advertID)
	ret0, _ := ret[0].(*models.Promotion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPromotionData indicates an expected call of GetPromotionData.
func (mr *MockAdvertsStorageInterfaceMockRecorder) GetPromotionData(ctx, advertID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPromotionData", reflect.TypeOf((*MockAdvertsStorageInterface)(nil).GetPromotionData), ctx, advertID)
}

// GetSuggestions mocks base method.
func (m *MockAdvertsStorageInterface) GetSuggestions(ctx context.Context, title string, num uint) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSuggestions", ctx, title, num)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSuggestions indicates an expected call of GetSuggestions.
func (mr *MockAdvertsStorageInterfaceMockRecorder) GetSuggestions(ctx, title, num interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSuggestions", reflect.TypeOf((*MockAdvertsStorageInterface)(nil).GetSuggestions), ctx, title, num)
}

// InsertView mocks base method.
func (m *MockAdvertsStorageInterface) InsertView(ctx context.Context, userID, advertID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertView", ctx, userID, advertID)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertView indicates an expected call of InsertView.
func (mr *MockAdvertsStorageInterfaceMockRecorder) InsertView(ctx, userID, advertID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertView", reflect.TypeOf((*MockAdvertsStorageInterface)(nil).InsertView), ctx, userID, advertID)
}

// SearchAdvertByTitle mocks base method.
func (m *MockAdvertsStorageInterface) SearchAdvertByTitle(ctx context.Context, title string, userID, startID, num uint) ([]*models.ReturningAdInList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchAdvertByTitle", ctx, title, userID, startID, num)
	ret0, _ := ret[0].([]*models.ReturningAdInList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchAdvertByTitle indicates an expected call of SearchAdvertByTitle.
func (mr *MockAdvertsStorageInterfaceMockRecorder) SearchAdvertByTitle(ctx, title, userID, startID, num interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchAdvertByTitle", reflect.TypeOf((*MockAdvertsStorageInterface)(nil).SearchAdvertByTitle), ctx, title, userID, startID, num)
}

// YuKassaUpdateDB mocks base method.
func (m *MockAdvertsStorageInterface) YuKassaUpdateDB(ctx context.Context, paymentList *models.PaymentList, advertID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "YuKassaUpdateDB", ctx, paymentList, advertID)
	ret0, _ := ret[0].(error)
	return ret0
}

// YuKassaUpdateDB indicates an expected call of YuKassaUpdateDB.
func (mr *MockAdvertsStorageInterfaceMockRecorder) YuKassaUpdateDB(ctx, paymentList, advertID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "YuKassaUpdateDB", reflect.TypeOf((*MockAdvertsStorageInterface)(nil).YuKassaUpdateDB), ctx, paymentList, advertID)
}
